# Implement KNN Algorithm ON Heart Dataset to Predict Disease or not

In [1]:
# Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,recall_score,precision_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv("/content/heart.csv")

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
df.shape

(1025, 14)

In [5]:
x=df.drop(columns="target",axis=1)
y=df["target"]

In [6]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [7]:
# Spliting the Data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [8]:
# Scale the values
scalar = StandardScaler()
x_train_scaled = scalar.fit_transform(x_train)
x_test_scaled = scalar.fit_transform(x_test)

In [9]:
# Train the model on KNN Algorithm
KNN_model = KNeighborsClassifier(n_neighbors=3)
KNN_model.fit(x_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [10]:
# Test the model on Testing Data
y_pred = KNN_model.predict(x_test_scaled)

In [11]:
# Evaluste the model
print(accuracy_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(precision_score(y_test,y_pred))

0.9365853658536586
0.9
0.967741935483871